# Generated by Django 5.1 on 2025-10-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_talk"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="icon",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
